export const SPECIAL_NAMES: string[] = [
  'deoxys',
  'lycanroc',
  'wishiwashi',
  'necrozma',
  'zygarde',
  'basculin',
  'darmanitan',
  'kyurem',
  'keldeo',
  'shaymin',
  'meloetta',
  'rotom',
  'minior',
  'mimikyu',
  'pikachu',
  'castform',
  'wormadam',
  'floette',
  'aegislash',
  'pumpkaboo',
  'gourgeist',
  'hoopa',
  'magearna',
  'cramorant',
  'toxtricity',
  'eiscue',
  'morpeko',
  'eternatus',
  'urshifu',
  'zarude',
  'calyrex',
  'ursaluna',
  'maushold',
  'squawkabilly',
  'tatsugiri',
  'dudunsparce',
  'gimmighoul',
  'ogerpon',
  'terapagos',
  'koraidon',
  'miraidon',
];

export const MODIFIER_MAP: Record<string, string> = {
  mega: 'Mega',
  gmax: 'Gigantamax',
  origin: 'Origin Forme',
  altered: 'Altered Forme',
  hisui: 'Hisuian',
  alola: 'Alolan',
  galar: 'Galarian',
  paldea: 'Paldean',
  sensu: 'Sensu',
  baile: 'Baile',
  totem: 'Totem',
  incarnate: 'Incarnate Forme',
  therian: 'Therian Forme',
  pau: "Pa'u",
  primal: 'Primal',
  male: 'Male',
  female: 'Female',
  crowned: 'Crowned',
  hero: 'Hero Forme',
  zero: 'Zero Forme',
  '10': '10%',
  '50': '50%',
};

export const NAME_OVERRIDES: Record<string, string> = {
  'greninja-battle-bond': 'Battle-Bond Greninja',
  'greninja-ash': 'Ash-Greninja',
  'mr-rime': 'Mr. Rime',
  'mr-mime': 'Mr. Mime',
  'mr-mime-galar': 'Galarian Mr. Mime',
  'oricorio-pom-pom': 'Pom-Pom Oricorio',
  'rockruff-own-tempo': 'Own Tempo Rockruff',
  'kommo-o-totem': 'Totem Kommo-O',
  'morpeko-full-belly': 'Full-Belly Morpeko',
};
